// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAokug78rxWez2LewCaDbPI20e4qlBbPro',
    appId: '1:657681276345:web:15a348c56b050319736a68',
    messagingSenderId: '657681276345',
    projectId: 'forpartum-620c4',
    authDomain: 'forpartum-620c4.firebaseapp.com',
    storageBucket: 'forpartum-620c4.appspot.com',
    measurementId: 'G-13F5B0P01C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3s103dEdobEjm5ZsiC0UxE8bqbmmQK7g',
    appId: '1:657681276345:android:2d33886ca4f4c500736a68',
    messagingSenderId: '657681276345',
    projectId: 'forpartum-620c4',
    storageBucket: 'forpartum-620c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4OagFLRklsYP4uKUfwNfdokABTQTHw8',
    appId: '1:657681276345:ios:7d595f7b4bd0340c736a68',
    messagingSenderId: '657681276345',
    projectId: 'forpartum-620c4',
    storageBucket: 'forpartum-620c4.appspot.com',
    iosClientId: '657681276345-hvqegd79gtd07q7d9854v8ql93rciaab.apps.googleusercontent.com',
    iosBundleId: 'com.rehman.forpartum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV4OagFLRklsYP4uKUfwNfdokABTQTHw8',
    appId: '1:657681276345:ios:ab3c42efa793654a736a68',
    messagingSenderId: '657681276345',
    projectId: 'forpartum-620c4',
    storageBucket: 'forpartum-620c4.appspot.com',
    iosClientId: '657681276345-2pl44hf320kbkppnk5klcmcosqniab5g.apps.googleusercontent.com',
    iosBundleId: 'com.rehman.forpartum.RunnerTests',
  );
}
